# Generated by Django 4.2.19 on 2025-03-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
    ]
