# Generated by Django 4.2.19 on 2025-03-05 17:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2010, 1, 1))]),
        ),
    ]
