# Generated by Django 4.2.16 on 2024-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='diversity',
            field=models.CharField(choices=[('VI', 'Visual'), ('MO', 'Motor'), ('CO', 'Cognitive'), ('HE', 'Hearing'), ('SE', 'Sensory')], default='VI', max_length=10),
        ),
    ]
