# Generated by Django 4.2.16 on 2024-11-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_opinion_game_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='opinion',
        ),
    ]
