# Generated by Django 4.2.16 on 2024-11-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_game_opinion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='trailer_url',
            new_name='trailer',
        ),
    ]
