# Generated by Django 4.2.18 on 2025-02-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=20)),
                ('web_server', models.CharField(choices=[('Apache', 'Apache'), ('Nginx', 'Nginx'), ('GoogleCloud', 'Google Cloud')], max_length=11)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Engineer', 'Engineer'), ('Manager', 'Manager'), ('Guest', 'Guest')], max_length=11)),
                ('sing_in', models.CharField(choices=[('Mail', 'Mail'), ('Payroll', 'Payroll'), ('Self-Service', 'Self-Service')], max_length=12)),
            ],
        ),
    ]
