# Generated by Django 4.2.18 on 2025-02-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_novell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novell',
            old_name='sing_in',
            new_name='sign_in',
        ),
    ]
