# Generated by Django 4.2.18 on 2025-02-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_sing_in_novell_sign_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novell',
            name='sign_in',
            field=models.CharField(choices=[('Mail', 'Mail'), ('Payroll', 'Payroll'), ('Self-Service', 'Self-Service')], max_length=200),
        ),
    ]
