# Generated by Django 4.2.18 on 2025-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_novell_sign_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novell',
            name='sign_in',
        ),
        migrations.AlterField(
            model_name='novell',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Engineer', 'Engineer'), ('Manager', 'Manager'), ('Guest', 'Guest')], max_length=200),
        ),
        migrations.AlterField(
            model_name='novell',
            name='web_server',
            field=models.CharField(choices=[('Apache', 'Apache'), ('Nginx', 'Nginx'), ('GoogleCloud', 'Google Cloud')], max_length=200),
        ),
    ]
