# Generated by Django 4.2.18 on 2025-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_novell_sign_in_alter_novell_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novell',
            name='sign_in',
            field=models.CharField(choices=[('Mail', 'Mail'), ('Payroll', 'Payroll'), ('Self-Service', 'Self-Service')], max_length=200, null=True),
        ),
    ]
