# Generated by Django 4.2.18 on 2025-02-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_novell_sign_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novell',
            name='sign_in',
        ),
    ]
