# Generated by Django 4.2.18 on 2025-02-05 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_novell_sign_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novell',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
