# Generated by Django 4.2.19 on 2025-02-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='artists')),
                ('songs', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('logo', models.ImageField(upload_to='logos')),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=250)),
                ('ticket_price', models.FloatField()),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.artist')),
            ],
        ),
    ]
