# Generated by Django 4.2.16 on 2024-11-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_rename_trailer_url_game_trailer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opinion',
            new_name='Detail',
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
