# Generated by Django 4.2.16 on 2024-11-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_rename_opinion_detail_alter_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='developer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detail',
            name='developerPage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='diversity',
            field=models.CharField(choices=[('Visual', 'Visual'), ('Motor', 'Motor'), ('Cognitive', 'Cognitive'), ('Hearing', 'Hearing'), ('Sensory', 'Sensory')], default='Visual', max_length=10),
        ),
    ]
