# Generated by Django 4.2.19 on 2025-02-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_games_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
